---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gancheng.
--- DateTime: 2021/12/5 15:46
---
local UIMgr = {}
local UIRoot

function UIMgr:Init()
    UIRoot = CS.Lavender.UI.LUIMgr.GetUIRoot()

end


function UIMgr:ActiveUI(windowName)

    local window = require("LavenderUI/Components/" .. windowName)
    local res = Roact.createElement(window)

    Roact.mount(res, UIRoot)

end


return UIMgr