---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gancheng.
--- DateTime: 2021/12/5 15:46
---
local UIMgr = {}




function UIMgr:ActiveUI()
    local testUI = Roact.createElement("Text",{},{
        testChild = Roact.createElement("Text")
    })
    Roact.mount(testUI)
    --CS.Lavender.UI.LUIElement.NewElement(ElementType.Text)
end


return UIMgr