---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gancheng.
--- DateTime: 2021/12/6 15:29
---

local BagWindow = Roact.Component:extend("BagWindow")
local BagItem = require("LavenderUI/Components/BagItem")

function BagWindow:init()
    self:setState({
        bagSlot = 5
    })
end

function BagWindow:render()
    local bagSlot = self.state.bagSlot
    local itemList = {}
    for i = 1, bagSlot do
        itemList[i] = Roact.createElement(BagItem)
    end
    return Roact.createElement("Image",{},itemList)
end

return BagWindow