---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gancheng.
--- DateTime: 2021/12/6 15:29
---

---@type BagItem
local BagItem = require("LavenderUI/Components/BagItem")
local Item = require("LavenderUI/Components/ComTest/Item")
local BagWindow = Roact.Component:extend("BagWindow")

function BagWindow:init()
    self:setState({
        bagSlot = 1
    })
end

function BagWindow:render()
    --self.outTest("resTable")
    --CS.UnityEngine.Debug.Log(self.resTable[1])
    local bagSlot = self.state.bagSlot
    local itemList = {}
    for i = 1, bagSlot do
        itemList["Item_" .. i] = Roact.createElement(Item,{
            position = CS.UnityEngine.Vector2(i * 60 - 10,  -60 * i + 10)
        })
    end
    return Roact.createElement("Image",{
        color = RGBA(1.000, 1.000, 1.000, 1.000),
        size = CS.UnityEngine.Vector2(800, 500)
    },itemList)
end

return BagWindow